export const SET_SEARCH_FIELD = 'SET_SEARCH_FIELD';
export const SET_REQUEST_PENDING = 'SET_REQUEST_PENDING';
export const SET_REQUEST_SUCCESS = 'SET_REQUEST_SUCCESS';
export const SET_REQUEST_FAILED = 'SET_REQUEST_FAILED';
export const CREATE_ROBOT = 'CREATE_ROBOT';
