export const CHANGE_INPUT_FIELD = 'CHANGE_INPUT_FIELD';
export const DETECT_FACE_REQUEST_PENDING = 'DETECT_FACE_REQUEST_PENDING';
export const DETECT_FACE_REQUEST_SUCCESS = 'DETECT_FACE_REQUEST_SUCCESS';
export const DETECT_FACE_REQUEST_FAILED = 'DETECT_FACE_REQUEST_FAILED';
export const ROUTE_HOME = 'ROUTE_HOME';
export const ROUTE_REGISTER = 'ROUTE_REGISTER';
export const ROUTE_SIGNIN = 'ROUTE_SIGNIN';
export const CLEAR_IMAGE = 'CLEAR_IMAGE';
export const SIGNIN_REQUEST_PENDING = 'SIGNIN_REQUEST_PENDING';
export const SIGNIN_REQUEST_SUCCESS = 'SIGNIN_REQUEST_SUCCESS';
export const SIGNIN_REQUEST_FAILED = 'SIGNIN_REQUEST_FAILED';
export const CHANGE_PASSWORD_SIGNIN = 'CHANGE_PASSWORD_SIGNIN';
export const CHANGE_EMAIL_SIGNIN = 'CHANGE_EMAIL_SIGNIN';
export const CLEAR_CHANGE_ROUTE_TO_HOME = 'CLEAR_CHANGE_ROUTE_TO_HOME';
export const CHANGE_EMAIL_REGISTER = 'CHANGE_EMAIL_REGISTER';
export const CHANGE_PASSWORD_REGISTER = 'CHANGE_PASSWORD_REGISTER';
export const CHANGE_NAME_REGISTER = 'CHANGE_NAME_REGISTER';
export const REGISTER_REQUEST_PENDING = 'REGISTER_REQUEST_PENDING';
export const REGISTER_REQUEST_SUCCESS = 'REGISTER_REQUEST_SUCCESS';
export const REGISTER_REQUEST_FAILED = 'REGISTER_REQUEST_FAILED';
export const CLEAR_REGISTER_STATE = 'CLEAR_REGISTER_STATE';
export const GET_USER_INFO = 'GET_USER_INFO';
export const PUT_SCORE = 'PUT_SCORE';






